//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

public class CrearPlanoTest : MonoBehaviour
{
	public List<ItemModelo> itemsATestear;
	public PlanoTest p ;
	public Material materialTexto;
	public Font fontTexto;

	public bool inicializado = false;

	public bool Inicializado()
	{
		return inicializado;
	}

	public void inicializar (){
		itemsATestear = new List<ItemModelo>();
		p = new PlanoTest (GameObject.Find ("panelTesting"));
	
	}
	public void limpiar()
	{
		if (p != null) {
			p.destruir();		
		}
	}

	public void setItems(List<ItemModelo> items)
	{
		p.destruir ();
		itemsATestear = items;
		p = new PlanoTest (GameObject.Find ("panelTesting"));
		crearPlano();
	}


	public void crearPlano()
	{
		foreach(ItemModelo i in itemsATestear){
			Text3DCuboItem item = new Text3DCuboItem(i);
			item.setMaterial (materialTexto);
			item.setFont (fontTexto);
			p.addElementoToTest(item);
		}
	}


}

