//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Sfs2X.Entities.Data;
using UnityEngine;



public class EjecucionTest : IComparable
{
		private string time = "";
		private string name = "";
		private string estado = "";
		private string mensaje = "";
		private string entorno = "";
		private string stacktrace = "";
		private DateTime fecha_hora;
		private string info_ejecucion = "" ;
		private long id_test; 


		public EjecucionTest(SFSObject s)
		{
			this.fromSFSObject (s);
		}

		public int CompareTo(object e)
		{
		EjecucionTest otroObjeto = e as EjecucionTest; 
		return this.getFechaHora ().CompareTo (otroObjeto.getFechaHora ());
		}


		public EjecucionTest (string time, string name, string result)
		{
			this.time = time;
			this.name = name;
			this.estado = result;
		}

		public void setIdTest(long id){
			this.id_test = id;
		}

		public long getIdTest()
		{
			return id_test;
		}

		public void setFechaHora(DateTime fh)
		{
			this.fecha_hora = fh;		
		}
		public void setInfo(){
			this.info_ejecucion = this.mensaje + "  " + this.stacktrace;

		
		}

		public void setMensaje(string m)
		{
			mensaje = m;
			setInfo ();
		}

		public void setStackTrace(string s)
		{
			stacktrace = s;		
			setInfo ();
		}

		public void setEntorno(string entorno)
		{
			this.entorno = entorno;	
		}


		public string getTime()
		{
			return time;
		}

		public string getName()
		{
			return name;
		}

		public string getEstado()
		{
			return estado;
		}

		public string getMensaje()
		{
			return mensaje;
		}

		public string getStacktrace()
		{
			return stacktrace;
		}

		public string getEntorno()
		{
			return entorno;
		}

		public DateTime getFechaHora()
		{
			return fecha_hora;
		}
		
		public string getInfoEjecucion()
		{
			return info_ejecucion;
		}

		public void setNombre(string n)
		{
			this.name = n;
		}

		public SFSObject toSFSObject() {
			
			SFSObject testEjecObject = new SFSObject();
			testEjecObject.PutLong("id_test", this.id_test);
			testEjecObject.PutUtfString("entorno", this.entorno);
			testEjecObject.PutUtfString("estado", this.estado);
			testEjecObject.PutUtfString("fecha_hora", this.fecha_hora.ToString());
			testEjecObject.PutUtfString("info_ejecucion", this.info_ejecucion);
			testEjecObject.PutUtfString("time", this.time);
			return testEjecObject;
		}
		
		public void fromSFSObject(SFSObject item){
			this.id_test = item.GetLong("id_test");
			this.fecha_hora = System.DateTime.Parse(item.GetUtfString("fecha_hora"));
			this.info_ejecucion = item.GetUtfString("info_ejecucion");
			if (info_ejecucion != null && !info_ejecucion.Equals ("")) {
				string m = info_ejecucion.Split ('^') [0];
				string s = info_ejecucion.Split ('^') [1];
				this.setMensaje (m.Substring (0, m.Length - 11));
				this.setStackTrace (s);
			}
			this.estado = item.GetUtfString("estado");
			this.entorno = item.GetUtfString("entorno");
			this.time = item.GetUtfString("time");
		}



	}


