//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

public class PlanoTest
{		
		public Cuadricula test;
		private GameObject gameObject;

	
		public PlanoTest (GameObject g)
		{
			gameObject = g;
			test = new Cuadricula (FindChild ("interiorTestBoard"));
			setBotones (test);
		}

		private void setBotones (Cuadricula c)
		{
			avanzarQuadTaskboard accion = (avanzarQuadTaskboard)c.FindChild ("back").GetComponent ("avanzarQuadTaskboard");
			accion.setCuadricula (c);
			accion = (avanzarQuadTaskboard)c.FindChild ("forward").GetComponent ("avanzarQuadTaskboard");
			accion.setCuadricula (c);
		}	

		public void destruir ()
		{
			test.borrarPlano ();
			test.destruir ();
		}

		public void addElementoToTest (Text3DCuboItem t)
		{
			test.addElemento (t);
		}
		
		public void borrarTareas(){
			test.borrarTareas();
		}
	
		void Start ()
		{	
			
		}
		
		// Update is called once per frame
		void Update ()
		{
			
		}

		public bool inicializado()
		{
			if (test.getCount()>0)
						return true;
				return false;
		}

		public GameObject FindChild (string pName)
		{
			Transform pTransform = gameObject.GetComponent<Transform> ();
			foreach (Transform trs in pTransform) {
				if (trs.gameObject.name == pName)
					return trs.gameObject;
			}
			return  null;
		}

}


