//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class ItemBehaviour : MonoBehaviour
{
	private Text3DCuboItem cuboItem;

	public void setCuboItem(Text3DCuboItem it)
	{
		cuboItem = it;
	}


	void OnMouseUpAsButton(){
		if (GUIUtility.hotControl == 0) {
			GUI_DetalleItemTest detalle = (GUI_DetalleItemTest)GetComponent ("GUI_DetalleItemTest");
			detalle.Mostrar ();
		}
	}
}


