//------------------------------------------------------------------------------
// <auto-generated>
//     Este cÃ³digo fue generado por una herramienta.
//     VersiÃ³n de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrÃ­an causar un comportamiento incorrecto y se perderÃ¡n si
//     se vuelve a generar el cÃ³digo.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Text3DCuboItem : Text3DCubo
{
	private ItemModelo item;


	public Text3DCuboItem(ItemModelo it) : base (it.getName())
	{
		item = it;
	}

	public override void dibujarObjetoEnQuad (GameObject padre,int fontsize){
		base.dibujarObjetoEnQuad(padre,fontsize);
		plano.AddComponent<ItemBehaviour>();
		ItemBehaviour script = (ItemBehaviour)plano.GetComponent("ItemBehaviour");
		script.setCuboItem(this);
		plano.AddComponent<GUI_DetalleItemTest>();
		GUI_DetalleItemTest detalle = (GUI_DetalleItemTest)plano.GetComponent("GUI_DetalleItemTest");
		detalle.setItem(this.item);
	}
				
}


