//------------------------------------------------------------------------------
// <auto-generated>
//     Este cÃ³digo fue generado por una herramienta.
//     VersiÃ³n de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrÃ­an causar un comportamiento incorrecto y se perderÃ¡n si
//     se vuelve a generar el cÃ³digo.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class usPlaneBehavior : MonoBehaviour
{
		private Text3DPlaneUS cubous;
		
		public void setCuboUS(Text3DPlaneUS us)
		{
			cubous = us;
		}
		
		
		
		void OnMouseDown(){
			if(GUIUtility.hotControl == 0){
				GameObject g = new GameObject();
				g.AddComponent<GUI_DetalleStory>();
				g.SendMessage("setUserStory", cubous.getUS());
				g.SendMessage("Mostrar");
			}
		}
}

