//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Sfs2X.Entities.Data;


namespace AssemblyCSharp
{
	public class AsociacionTareaTest
	{
		private long Id_Test;
		private long Id_Tarea;
			
		public AsociacionTareaTest (long id_tarea, long id_test)
		{
			Id_Test = id_test;
			Id_Tarea = id_tarea;
		}

		public SFSObject toSFSObject ()
		{			
			SFSObject asocObject = new SFSObject ();
			asocObject.PutLong ("Id_Test", Id_Test);
			asocObject.PutLong ("Id_Task", Id_Tarea);
			return asocObject;
		}
	}
}

